platform :ios, '7.0'

pod 'Dropbox-Sync-API-SDK', '~> 3.1.2'
pod 'UIAlertView+Blocks', '~> 0.8.1'
pod 'libextobjc/EXTScope', '~> 0.4.1'
pod 'CocoaSecurity', '~> 1.2.2'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'NYXImagesKit', '~> 2.3'
pod 'Appirater', '~> 2.0.4'
pod 'CrashlyticsFramework', '~> 2.2.5.2'
pod 'MBProgressHUD', '~> 0.8'
